name: Release Extension

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0, v1.1.0, etc.

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Update manifest.json version
        run: |
          cd extension
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.version.outputs.VERSION }}\"/" manifest.json
      
      - name: Package extension
        run: |
          cd extension
          zip -r ../swagger-to-scalar-v${{ steps.version.outputs.VERSION }}.zip . -x "*.DS_Store" -x "__MACOSX"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: swagger-to-scalar-v${{ steps.version.outputs.VERSION }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

